version: "3.3"
services:
  pg:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - "./oscar.sql:/docker-entrypoint-initdb.d/oscar.sql"
  hw14:
    build: .
    depends_on:
      - pg

